// ============================================================
// MANAGER STAFF MODULE - Personnel directory CRUD
// ============================================================

let cachedRosteredStaffArray = [];
let pendingDeletionTargetEmployeeId = null;

async function fetchRosteredStaffProfiles() {
    const tbody = document.getElementById('staffDirectoryTableBody');
    if (!tbody) return;
    tbody.innerHTML = '<tr><td colspan="5">Synchronizing employee table columns...</td></tr>';

    try {
        const response = await fetch(`${API_BASE_URL}manager/staff_list`);
        const data = await response.json();
        cachedRosteredStaffArray = data.items || [];

        if (cachedRosteredStaffArray.length === 0) {
            tbody.innerHTML = '<tr><td colspan="5" style="text-align:center; color:var(--text-muted);">No active employee records found on disk.</td></tr>';
            return;
        }

        tbody.innerHTML = cachedRosteredStaffArray.map(emp => {
            // FAULT TOLERANT MAPPING: Captures both uppercase and lowercase keys generated by ORDS
            const empNum = emp.EMPLOYEE_NUM || emp.employee_num || '';
            const empName = emp.EMPLOYEE_NAME || emp.employee_name || 'Unnamed';
            const empType = String(emp.EMPLOYEE_TYPE || emp.employee_type || 'Runner').toUpperCase();
            const managerNum = emp.MANAGER_NUM || emp.manager_num || 'SYSTEM';

            return `
                <tr>
                    <td class="history-order-id">${empNum}</td>
                    <td><strong>${empName}</strong></td>
                    <td><span class="cart-item-qty">${empType}</span></td>
                    <td><span style="color:var(--text-muted); font-family:monospace;">${managerNum}</span></td>
                    <td style="text-align: right;">
                        <button type="button" class="btn-reorder" style="border-color: var(--danger); color: var(--danger);" 
                                onclick="openDeleteStaffModal('${empNum}')">
                            Delete Profile
                        </button>
                    </td>
                </tr>
            `;
        }).join('');
    } catch (e) {
        console.error("Staff module rendering mismatch:", e);
        tbody.innerHTML = '<tr><td colspan="5" style="color:var(--danger);">Error reading data rows.</td></tr>';
    }
}

function openAddStaffModal() {
    document.getElementById('addStaffModalOverlay').classList.add('open');
}

function closeAddStaffModal() {
    document.getElementById('addStaffModalOverlay').classList.remove('open');
}

async function handleCreateStaffSubmit(event) {
    event.preventDefault();
    const payload = {
        employee_name: document.getElementById('txtNewStaffName').value.trim(),
        employee_type: document.getElementById('ddlNewStaffRole').value,
        manager_num: document.getElementById('ddlNewStaffManager').value,
        employee_password: 'password123'
    };

    try {
        const response = await fetch(`${API_BASE_URL}manager/add_staff`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: new URLSearchParams(payload)
        });

        const data = await response.json();
        if (data.status === 'success' || data.STATUS === 'success') {
            alert("Personnel added successfully using seq_employee trigger context!");
            closeAddStaffModal();
            document.getElementById('txtNewStaffName').value = '';
            fetchRosteredStaffProfiles();
        }
    } catch (e) {
        alert("Error mapping insert action parameters to database layout.");
    }
}

function openDeleteStaffModal(employeeNum) {
    // Check both potential key contexts for finding matches
    const staffRecord = cachedRosteredStaffArray.find(x => 
        (x.EMPLOYEE_NUM || x.employee_num) === employeeNum
    );
    if (!staffRecord) return;

    pendingDeletionTargetEmployeeId = employeeNum;

    const empNum = staffRecord.EMPLOYEE_NUM || staffRecord.employee_num || '';
    const empName = staffRecord.EMPLOYEE_NAME || staffRecord.employee_name || '';
    const empType = String(staffRecord.EMPLOYEE_TYPE || staffRecord.employee_type || '').toUpperCase();

    document.getElementById('lblDelStaffNum').textContent = empNum;
    document.getElementById('lblDelStaffName').textContent = empName;
    document.getElementById('lblDelStaffRole').textContent = empType;
    document.getElementById('txtManagerVerificationPassword').value = '';

    document.getElementById('deleteStaffVerificationModalOverlay').classList.add('open');
}

function closeDeleteStaffModal() {
    const modal = document.getElementById('deleteStaffVerificationModalOverlay');
    if (modal) modal.classList.remove('open');
    pendingDeletionTargetEmployeeId = null;
}

async function handleExecuteDeleteStaffSubmit(event) {
    event.preventDefault();
    const verificationPass = document.getElementById('txtManagerVerificationPassword').value;

    const payload = {
        manager_id: currentManagerId,
        manager_password: verificationPass,
        target_employee_id: pendingDeletionTargetEmployeeId
    };

    try {
        const response = await fetch(`${API_BASE_URL}manager/delete_staff`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: new URLSearchParams(payload)
        });

        const data = await response.json();

        if (data.status === 'success' || data.STATUS === 'success') {
            closeDeleteStaffModal();
            triggerFloatingSuccessToastNotification('Employee removed successfully');
            fetchRosteredStaffProfiles();
        } else {
            alert("Security Verification Mismatch: " + (data.message || data.MESSAGE || "Unauthorized operation index"));
        }
    } catch (err) {
        alert("Transaction processing timeout clearing data row components.");
    }
}

window.fetchRosteredStaffProfiles = fetchRosteredStaffProfiles;
window.openAddStaffModal = openAddStaffModal;
window.closeAddStaffModal = closeAddStaffModal;
window.handleCreateStaffSubmit = handleCreateStaffSubmit;
window.openDeleteStaffModal = openDeleteStaffModal;
window.closeDeleteStaffModal = closeDeleteStaffModal;
window.handleExecuteDeleteStaffSubmit = handleExecuteDeleteStaffSubmit;